package:
  name: fiji
  version: 20200810

source:
  -   url: https://downloads.imagej.net/fiji/archive/20200810-1942/fiji-linux64.zip  # [linux]
      md5: 1aaa2d11daac043cb0e63d00c8c79253   # [linux]
  -   url: https://downloads.imagej.net/fiji/archive/20200810-1942/fiji-macosx.zip # [osx]
      md5: a5c9af6c0ced968931faa3280e2394e1   # [osx]

build:
  number: 1

requirements:
  host:
    - openjdk >=8.0
  run:
    - openjdk >=8.0

test:
  files:
    - hello.py
  commands:
    # (see run_test.sh for remainder of tests)
    - bunwarpj 2>&1 | grep 'Usage'
    - ImageJ --help 2>&1 | grep ImageJ

about:
  home: http://fiji.sc
  license: GNU General Public License
  summary: Fiji is an image processing package—a "batteries-included" distribution of ImageJ, bundling a lot of plugins which facilitate scientific image analysis.

extra:
  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
